<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="7" hostname="rstl006-pc" name="test.NewTest" tests="8" failures="0" timestamp="19 Mar 2019 08:49:14 GMT" time="0.023" errors="1">
  <testcase name="f" time="0.000" classname="test.NewTest">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="beforetestSSM" time="0.023" classname="test.NewTest">
    <error type="java.io.FileNotFoundException" message="Test-Input\Login.properties (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: Test-Input\Login.properties (The system cannot find the path specified)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileInputStream.<init>(FileInputStream.java:93)
at test.NewTest.beforetestSSM(NewTest.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforetestSSM -->
  <testcase name="BackPI" time="0.000" classname="test.NewTest">
    <skipped/>
  </testcase> <!-- BackPI -->
  <testcase name="RemovePharmacy" time="0.000" classname="test.NewTest">
    <skipped/>
  </testcase> <!-- RemovePharmacy -->
  <testcase name="ADDNewPharmacy" time="0.000" classname="test.NewTest">
    <skipped/>
  </testcase> <!-- ADDNewPharmacy -->
  <testcase name="ADDBackPI" time="0.000" classname="test.NewTest">
    <skipped/>
  </testcase> <!-- ADDBackPI -->
  <testcase name="ADDResetPI" time="0.000" classname="test.NewTest">
    <skipped/>
  </testcase> <!-- ADDResetPI -->
  <testcase name="RemovePharmacyVerify" time="0.000" classname="test.NewTest">
    <skipped/>
  </testcase> <!-- RemovePharmacyVerify -->
</testsuite> <!-- test.NewTest -->
